---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.6.0-jdk-8-alpine

inputs:
  - name: source-code

run:
  path: "mvn"
  args:
    - -f
    - source-code/pom.xml
    - clean
    - compile