---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.8.1-jdk-11-openj9

inputs:
  - name: feature-branch-source-code

run:
  path: "mvn"
  args:
    - -f
    - feature-branch-source-code/pom.xml
    - clean
    - compile
    - test