---
resource_types:
- name: git-multibranch
  type: docker-image
  source:
    repository: cfcommunity/git-multibranch-resource

resources:
- name: feature-branch-source-code
  type: git-multibranch
  source:
    uri: https://github.com/shivamgupta-sg/Maven_Assignment
    branches: '.feature*'
    ignore_branches: '(main)'

- name: main-branch-source-code
  type: git-multibranch
  source:
    uri: https://github.com/shivamgupta-sg/Maven_Assignment
    branches: '.main'
    # ignore_branches: '(main)'

jobs:
- name: building-multibranch
  plan: 
  - get: feature-branch-source-code
  - get: main-branch-source-code
  
  - task: main-branch-task
    file: "source-code/concourse-ci/tasks/maven-compile.yml"
  - task: feature-branch-task
    file: "source-code/concourse-ci/tasks/maven-compile.yml"












# ---
# resource_types:
# - name: git-multibranch
#   type: docker-image
#   source:
#     repository: cfcommunity/git-multibranch-resource

# resources:
# - name: multibranch-source-code
#   type: git-multibranch
#   source:
#     uri: https://github.com/shivamgupta-sg/Maven_Assignment
#     branches: '.*'
#     # ignore_branches: '(main)'

# - name: source-code
#   type: git
#   source:
#     uri: https://github.com/shivamgupta-sg/Maven_Assignment
#     branch: main

# jobs:
#   - name: unit-test
#     plan:
#       - in_parallel:    
#         - get: source-code
#           trigger: true
#         - get: multibranch-source-code
#           trigger: true
#       - task: checking-pwd
#         config:
#           platform: linux
#           image_resource:
#             type: docker-image
#             source:
#               repository: ubuntu
#           run:
#             path: pwd
#       - task: getting-source-code
#         config:
#           platform: linux
#           image_resource:
#             type: docker-image
#             source:
#               repository: ubuntu
#           inputs:
#           - name: source-code
#           run:
#             path: find
#             args:
#             - .
#       - task: mvn-compile
#         file: "source-code/concourse-ci/tasks/maven-compile.yml"

#     #   - task: compile-code
#     #     config:
#     #       platform: linux
#     #       image_resource:
#     #         type: docker-image
#     #         source:
#     #           repository: maven

#     #       inputs:
#     #         - name: source-code

#     #       run:
#     #         path: mvn
#     #         args:
#     #           - source-code/pom.xml
#     #           - clean
#     #           - compile
